### ISSUE TITLE
I have a question about the vpn part.

### ISSUE THREAD

**Issue by QuinnCoolGuy** [Bonfire-GTK/newpirates#6]
I live in the U.S. and I would like to know where I should connect the VPN too and if you know any free good VPNs to recommend?

**Comment by dragonhunter056** [comment]
I know you asked this a long time ago but I'll answer for anyone else that's new and wondering this.
1. I don't think it matters much where you connect too so long as you're using a VPN.
2. There are no Good Free VPNs if any say their free then chances are they will sell your data. I think Windscribe has a free option but its limited to 2GB a day.
